export class Dog {
    data: object;
    // header
    header: object;
    navList: object;
    svg: string;
    nav: string;
    // footer
    footer: object;
    // default
    default: object;
    quote: string;
    desList: any;
    // info
    info: object;
    infoList: object;
    icon: string;
    key: string;
    value: string;
    // skill
    skill: object;
    outCircleList: object;
    color: string;
    name: string;
    innerCircleList: object;
    // works
    works: object;
    worksList: object;
    des: string;
    url: string;
    viewMore: string;
    // experience
    expList: object;
    time: string;
    post: string;
    imgUrl: string;
    tech: string;
    contentList: object;
    // contact
    contact: object;
    desList1: object;
    desList2: object;
    download: string;
    fileList: object;
    typeList: object;
}
